<link rel="stylesheet" href="style/css/cssProfile.css" type="text/css" media="screen, projection">
<script src="style/js/jquery-3.2.1.min.js"></script>
<script src="style/js/jsProfile.js"></script>

<?php 
$formUser = $this->form;

$nameLabel = $formUser->name->getLabel();
$name = $formUser->name;
$nameErr = $formUser->name->getMessages();
$ageLabel = $formUser->age->getLabel();
$age = $formUser->age;
$ageErr = $formUser->age->getMessages();
$btnShow = $formUser->Show;
$btnAdd = $formUser->Add;
$btnUpdate = $formUser->Update;
?>
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>index</b></p>
	<div id="control">
	<form method="post" id="profileForm" action="">
		<table>
			<tr>
				<td><?php echo $nameLabel; ?></td>
				<td><?php echo $name; ?></td>
			</tr>
			<tr id="nameErr">
				<td id="tdNameErr" colspan="2">
					<?php foreach ($nameErr as $message) :?>
						<p><?php echo $message ?></p>
					<?php endforeach;?>
				</td>
			</tr>
			<tr>
				<td><?php echo $ageLabel; ?></td>
				<td><?php echo $age; ?></td>
			</tr>
			<tr id="ageErr">
				<td id="tdAgeErr" colspan="2">
					<?php foreach ($ageErr as $message) :?>
						<p><?php echo $message ?></p>
					<?php endforeach;?>
				</td>
			</tr>
			<tr>
				<td colspan="2">
				<?php echo $btnAdd; ?>
				<?php echo $btnUpdate; ?>
				</td>
			</tr>
		</table>
		</form>
	</div>
	<div id="view">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Age</th>
				</tr>
			</thead>
			<tbody id="lineInfo">
			<tr class="rowUserInfo" id="sadfsd111"><td>sadfsad</td></tr>
			<?php 
				$users = $this->users; /* @var $users UserController */
				foreach($users as $user) : 
					$userName = $user['name'];
					$userAge = $user['age'];
					$userId = $user['id'];
				?>
				<tr id="<?php echo $userId ?>" class="rowUserInfo" >
					<td><?php echo $userName?></td>
					<td><?php echo $userAge ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>