<link rel="stylesheet" href="style/css/cssProfile.css" type="text/css" media="screen, projection">
<script src="style/js/jquery-3.2.1.min.js"></script>
<script src="style/js/jsProfile.js"></script>

<?php 
$formUser = $this->form;

$nameLabel = $formUser->name->getLabel();
$name = $formUser->name;
$nameErr = $formUser->name->getMessages();
var_dump($nameErr);
$ageLabel = $formUser->age->getLabel();
$age = $formUser->age;
$btnShow = $formUser->Show;
$btnAdd = $formUser->Add;
$btnUpdate = $formUser->Update;
?>
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>index</b></p>
	<div id="control">
	<form method="post" action="">
		<table>
			<tr>
				<td><?php echo $nameLabel; ?></td>
				<td><?php echo $name; ?></td>
			</tr>
			<tr>
				<td><?php echo $ageLabel; ?></td>
				<td><?php echo $age; ?></td>
			</tr>
			<tr>
				<td colspan="2">
				<?php echo $btnShow; ?>
				<?php echo $btnAdd; ?>
				<?php echo $btnUpdate; ?>
				</td>
			</tr>
		</table>
		</form>
	</div>
	<div id="view">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Age</th>
				</tr>
			</thead>
			<tbody id="lineInfo">
			
			</tbody>
		</table>
	</div>
</div>